### ISSUE TITLE
Does not lemmatize all

### ISSUE THREAD

**Issue by rabinpoudyal** [yohasebe/lemmatizer#13]
things returns things. does not work for that word.

**Comment by rabinpoudyal** [comment]
2.7.2 :004 > lemma.lemma("things")
 => "things"

**Comment by yohasebe** [comment]
Hi. Sorry for the inconvenience, but this is to be expected. The library uses Wordnet's lemmatization dictionary, and if the dictionary contains plurals like "things", that's what will be output as a result. please refer to the README for [possible solutions](https://github.com/yohasebe/lemmatizer#supplying-with-user-dict).

**Comment by yohasebe** [comment]
I suppose I can close this issue.
