### ISSUE TITLE
How about ablility to detect part of speech?

### ISSUE THREAD

**Issue by nvoynov** [yohasebe/lemmatizer#4]
Hi, developer. 

Very helpful gem, thanks!

I just finished something like wordextractor gem with some features and I just was playing around an idea of detection phrasal verbs from text by analyzing templates  `verb + preposition; verb + pronoun + preposition; verb + pronoun + preposition`.

I thought to add function to detect part of speech.

``` ruby
def pos(w)
  a = []
  [:noun, :verb, :adj, :adv].each { |p| a << p if lemma(w, p) }
  a.join(', ')
end
```

But in gem documentation and in sources I see that it always returns my input parameter when not found.

``` ruby
p lem.lemma("at", :noun) #=> at
p lem.lemma("in", :noun) #=> in
```

Can you provide something like method pos(word) which will return all part of speech for word?

**Comment by ParthKolekar** [comment]
@nvoynov 

You should be able to use https://github.com/yohasebe/engtagger to get those. (same author)
