### ISSUE TITLE
Adding custom dictionaries

### ISSUE THREAD

**Issue by jywarren** [yohasebe/lemmatizer#5]
Is there a means to point to additional dictionaries supplied at initialization, like `Lemmatizer.new(['path/to/dict'])` or `Lemmatizer.new(dictHash)`?

**Comment by jywarren** [comment]
This would be helpful for extending this to new languages or domain-specific vocabularies!

**Comment by yohasebe** [comment]
Good idea. I updated the code and README. Thanks for your suggestion.

**Comment by jywarren** [comment]
thank you!!! Amazing!
