### ISSUE TITLE
spaces in dict entries?

### ISSUE THREAD

**Issue by jywarren** [yohasebe/lemmatizer#7]
We're adding custom dictionaries as in #5, but weren't sure if we could put a phrase into quotation marks so that two words can be shown to be associated, like:

```
h2s "Hydrogen Sulphide"
data-logging "data logging"
cafo "factory farm"
```

We're using this for synonyms, which I know isn't the original use case, but curious if the gem supports this syntax, or could be made to? Thank you!

**Comment by yohasebe** [comment]
I have made a quick hack. Check out 0.2.2. Now you can do what you are trying to do, I hope. See README for details.

**Comment by jywarren** [comment]
Awesome! Thank you!

**Comment by jywarren** [comment]
https://github.com/yohasebe/lemmatizer#resolving-abbreviations
